# Usa a imagem oficial do Python
FROM python:3.9-slim

# Copia o script para o container
COPY hello.py /app/hello.py

# Define o diretório de trabalho
WORKDIR /app

# Comando padrão ao executar o container
CMD ["python", "hello.py"]